//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Big3.Hitbase.MainWindowDesigner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Big3.Hitbase.MainWindowDesigner.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausrichten.
        /// </summary>
        internal static string Align {
            get {
                return ResourceManager.GetString("Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die angegebene Archivnummer ist bereits vorhanden..
        /// </summary>
        internal static string ArchiveNumberAlreadyExists {
            get {
                return ResourceManager.GetString("ArchiveNumberAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Standard-Dialog kann nicht gelöscht werden..
        /// </summary>
        internal static string CanNotDeleteStandardDialog {
            get {
                return ResourceManager.GetString("CanNotDeleteStandardDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie hier, um ein Back-Cover hinzuzufügen..
        /// </summary>
        internal static string ChooseBackCover {
            get {
                return ResourceManager.GetString("ChooseBackCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie hier, um ein Front-Cover hinzuzufügen..
        /// </summary>
        internal static string ChooseFrontCover {
            get {
                return ResourceManager.GetString("ChooseFrontCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie hier, um ein CD-Label-Cover hinzuzufügen..
        /// </summary>
        internal static string ChooseLabelCover {
            get {
                return ResourceManager.GetString("ChooseLabelCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommentar.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben den Designmodus aktiviert. In diesem Modus haben Sie die Möglichkeit, den Dialog (Hauptmaske) nach Ihren Wünschen individuell anzupassen.
        ///
        ///Sie können z.B. neue Felder hinzufügen, oder vorhandene Felder verschieben oder löschen. Um ein neues Feld hinzuzufügen, markieren Sie es in der Toolbox und klicken Sie dann auf die gewünschte Stelle im Hauptfenster. Um ein Feld zu verschieben oder zu löschen, klicken Sie mit der Maus auf das Steuerelement im Hauptfenster. 
        ///
        ///Um den Designmodus zu verlassen, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DesignModeInfo {
            get {
                return ResourceManager.GetString("DesignModeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog definiert?.
        /// </summary>
        internal static string DialogDefined {
            get {
                return ResourceManager.GetString("DialogDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesen Hinweis nicht mehr zeigen.
        /// </summary>
        internal static string DontShowAgain {
            get {
                return ResourceManager.GetString("DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Dialog konnte nicht gelöscht werden..
        /// </summary>
        internal static string ErrorDeleteDialog {
            get {
                return ResourceManager.GetString("ErrorDeleteDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML-Dateien (*.xml)|*.xml|Alle Dateien (*.*)|*.*||.
        /// </summary>
        internal static string FileFilterXML {
            get {
                return ResourceManager.GetString("FileFilterXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie hier, um die angegebene Homepage zu öffnen..
        /// </summary>
        internal static string GoToHomepage {
            get {
                return ResourceManager.GetString("GoToHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Knoten &quot;HitbaseDialogData&quot; wurde nicht gefunden..
        /// </summary>
        internal static string HitbaseDialogDataNotFound {
            get {
                return ResourceManager.GetString("HitbaseDialogDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsche Versionsnummer..
        /// </summary>
        internal static string IllegalVersion {
            get {
                return ResourceManager.GetString("IllegalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Felder....
        /// </summary>
        internal static string MoreFields {
            get {
                return ResourceManager.GetString("MoreFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschieben.
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie hier, um die nächste freie Archivnummer zu ermitteln..
        /// </summary>
        internal static string NextFreeArchiveNumber {
            get {
                return ResourceManager.GetString("NextFreeArchiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Lesen des Dialogs trat ein Fehler auf. Möglicherweise ist es kein Hitbase-Dialog.
        ///
        ///Interne Fehlermeldung: {0}.
        /// </summary>
        internal static string NoHitbaseDialog {
            get {
                return ResourceManager.GetString("NoHitbaseDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfügen.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschaft geändert.
        /// </summary>
        internal static string PropertyChanged {
            get {
                return ResourceManager.GetString("PropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie den Dialog für die Kategorie &apos;{0}&apos; löschen?
        ///
        ///ACHTUNG: Das Löschen kann nicht rückgängig gemacht werden..
        /// </summary>
        internal static string QueryDeleteDialog {
            get {
                return ResourceManager.GetString("QueryDeleteDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Größe verändern.
        /// </summary>
        internal static string Resize {
            get {
                return ResourceManager.GetString("Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Suchbegriff &apos;{0}&apos; wurde nicht gefunden..
        /// </summary>
        internal static string SearchStringNotFound {
            get {
                return ResourceManager.GetString("SearchStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        internal static string TrackNumber {
            get {
                return ResourceManager.GetString("TrackNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML-Dateien (*.xml)|*.xml|Alle Dateien (*.*)|*.*||.
        /// </summary>
        internal static string XmlFileDialogFilter {
            get {
                return ResourceManager.GetString("XmlFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
