//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Big3.Hitbase.CatalogView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Big3.Hitbase.CatalogView.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll die Schreibweise der Interpreten und Titel automatisch an die Standardeinstellung angepasst werden?.
        /// </summary>
        internal static string AdjustSpelling {
            get {
                return ResourceManager.GetString("AdjustSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Alben.
        /// </summary>
        internal static string AlbumCountMultiple {
            get {
                return ResourceManager.GetString("AlbumCountMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Album.
        /// </summary>
        internal static string AlbumCountSingle {
            get {
                return ResourceManager.GetString("AlbumCountSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die angegebene Archivnummer ist bereits vorhanden..
        /// </summary>
        internal static string ArchiveNumberAlreadyExists {
            get {
                return ResourceManager.GetString("ArchiveNumberAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpret.
        /// </summary>
        internal static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Interpret(en).
        /// </summary>
        internal static string ArtistCount {
            get {
                return ResourceManager.GetString("ArtistCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese CD liegt momentan in einem CD-Laufwerk. Sie können die CD erst löschen, nachdem Sie sie aus dem Laufwerk entfernt haben..
        /// </summary>
        internal static string CantDeleteWhileCDIsInDrive {
            get {
                return ResourceManager.GetString("CantDeleteWhileCDIsInDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} CD(s).
        /// </summary>
        internal static string CDCount {
            get {
                return ResourceManager.GetString("CDCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog-Zusammenfassung.
        /// </summary>
        internal static string CDList {
            get {
                return ResourceManager.GetString("CDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesetzt.
        /// </summary>
        internal static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie aus der folgenden Liste aus, welche Felder gedruckt werden sollen:.
        /// </summary>
        internal static string ChooseFieldsForPrinting {
            get {
                return ResourceManager.GetString("ChooseFieldsForPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musikdatei auswählen.
        /// </summary>
        internal static string ChooseSoundfile {
            get {
                return ResourceManager.GetString("ChooseSoundfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuell eingelegte CD.
        /// </summary>
        internal static string CurrentCD {
            get {
                return ResourceManager.GetString("CurrentCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sollen wirklich alle CDs des Interpreten &quot;{0}&quot; gelöscht werden?.
        /// </summary>
        internal static string DeleteAllCDsOfArtist {
            get {
                return ResourceManager.GetString("DeleteAllCDsOfArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie diese CD wirklich löschen?
        ///
        ///Interpret: {0}
        ///Titel: {1}.
        /// </summary>
        internal static string DeleteCD {
            get {
                return ResourceManager.GetString("DeleteCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie diese {0} CDs wirklich löschen?.
        /// </summary>
        internal static string DeleteMultipleCDs {
            get {
                return ResourceManager.GetString("DeleteMultipleCDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie die diesem Track zugeordnete Musikdatei wirklich löschen? ({0}).
        /// </summary>
        internal static string DeleteSoundfile {
            get {
                return ResourceManager.GetString("DeleteSoundfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaillierte Katalog-Informationen.
        /// </summary>
        internal static string DetailList {
            get {
                return ResourceManager.GetString("DetailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende der Liste.
        /// </summary>
        internal static string EndOfList {
            get {
                return ResourceManager.GetString("EndOfList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter: {0}.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitbase Kataloge (*.hdbx)|*.hdbx|Alle Dateien (*.*)|*.*||.
        /// </summary>
        internal static string FilterHitbase {
            get {
                return ResourceManager.GetString("FilterHitbase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musikdateien (*.wav;*.mp3;*.wma;*.asf;*.ogg;*.flac)|*.wav;*.mp3;*.wma;*.asf;*.ogg;*.flac|Wave-Dateien (*.wav)|*.wav|MP3-Dateien (*.mp3)|*.mp3|Windows Media Audio-Dateien (*.wma;*.asf)|*.wma;*.asf|Ogg vorbis (*.ogg)|*.org|FLAC-Dateien (*.flac)|*.flac|Alle Dateien (*.*)|*.*.
        /// </summary>
        internal static string FilterSoundfile {
            get {
                return ResourceManager.GetString("FilterSoundfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Gruppierung.
        /// </summary>
        internal static string GroupingOff {
            get {
                return ResourceManager.GetString("GroupingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste der ausgeliehenen CDs.
        /// </summary>
        internal static string LoanedCDList {
            get {
                return ResourceManager.GetString("LoanedCDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liedtext nicht gefunden..
        /// </summary>
        internal static string LyricsNotFound {
            get {
                return ResourceManager.GetString("LyricsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Original-CDs.
        /// </summary>
        internal static string NoOriginalCDs {
            get {
                return ResourceManager.GetString("NoOriginalCDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Sampler.
        /// </summary>
        internal static string NoSampler {
            get {
                return ResourceManager.GetString("NoSampler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seite {0} von {1}.
        /// </summary>
        internal static string NumberOfPages {
            get {
                return ResourceManager.GetString("NumberOfPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur Original-CDs.
        /// </summary>
        internal static string OnlyOriginalCDs {
            get {
                return ResourceManager.GetString("OnlyOriginalCDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seite.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD.
        /// </summary>
        internal static string PrintCD {
            get {
                return ResourceManager.GetString("PrintCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpreten umbenennen.
        /// </summary>
        internal static string RenameArtist {
            get {
                return ResourceManager.GetString("RenameArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liedtext wird gesucht....
        /// </summary>
        internal static string SearchLyrics {
            get {
                return ResourceManager.GetString("SearchLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortiert nach: {0}.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} von {1} Datensätze gedruckt.
        /// </summary>
        internal static string TotalPrinted {
            get {
                return ResourceManager.GetString("TotalPrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        internal static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Track(s).
        /// </summary>
        internal static string TrackCount {
            get {
                return ResourceManager.GetString("TrackCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track-Liste.
        /// </summary>
        internal static string TrackList {
            get {
                return ResourceManager.GetString("TrackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track {0}.
        /// </summary>
        internal static string TrackNumber {
            get {
                return ResourceManager.GetString("TrackNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        internal static string Tracks {
            get {
                return ResourceManager.GetString("Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht gesetzt.
        /// </summary>
        internal static string Unchecked {
            get {
                return ResourceManager.GetString("Unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganze Seite.
        /// </summary>
        internal static string WholePage {
            get {
                return ResourceManager.GetString("WholePage", resourceCulture);
            }
        }
    }
}
