//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Big3.Hitbase.Statistics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Big3.Hitbase.Statistics.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Häufig genutzte Statistiken.
        /// </summary>
        internal static string TEXT_OVERVIEW {
            get {
                return ResourceManager.GetString("TEXT_OVERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl CDs gruppiert nach Kategorie .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_1 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl CDs gruppiert nach Aufnahmejahr .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_10 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl CDs gruppiert nach Interpretenart .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_11 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl CDs gruppiert nach Geschlecht .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_12 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl CDs gruppiert nach Land .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_13 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Tracks gruppiert nach Länge .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_14 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Tracks gruppiert nach Aufnahmejahr .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_15 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Tracks gruppiert nach Bewertung .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_16 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Tracks gruppiert nach BPM .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_17 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die meisten Tracks eines Interpreten .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_18 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Tracks gruppiert nach Geschlecht von Interpreten .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_19 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl CDs gruppiert nach Medium .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_2 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Tracks gruppiert nach Kennzeichen .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_20 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Tracks gruppiert nach Ländern .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_21 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Tracks gruppiert nach Art des Interpreten .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_22 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die meisten CDs eines Interpreten .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_23 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl CDs gruppiert nach Geschlecht eines Interpreten .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_24 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl CDs gruppiert nach Ländern .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_25 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl CDs gruppiert nach Art des Interpreten .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_26 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl CDs gruppiert nach Preis .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_3 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl CDs gruppiert nach Tracks .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_4 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl CDs gruppiert nach Gesamtlänge .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_5 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl CDs gruppiert nach Sampler .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_6 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl CDs gruppiert nach Bewertung .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_7 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl CDs gruppiert nach Kennzeichen .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_8 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl CDs gruppiert nach Label .
        /// </summary>
        internal static string TEXT_STATISTICS_GRAF_9 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS_GRAF_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summe der Tracklängen.
        /// </summary>
        internal static string TEXT_STATISTICS1 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchschnittliche Länge der CD.
        /// </summary>
        internal static string TEXT_STATISTICS10 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Längste CD.
        /// </summary>
        internal static string TEXT_STATISTICS11 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kürzeste CD.
        /// </summary>
        internal static string TEXT_STATISTICS12 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl der Interpreten.
        /// </summary>
        internal static string TEXT_STATISTICS13 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl der CD Sets.
        /// </summary>
        internal static string TEXT_STATISTICS14 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl der nicht zugewiesenen CDs.
        /// </summary>
        internal static string TEXT_STATISTICS15 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl der zugewiesenen CDs.
        /// </summary>
        internal static string TEXT_STATISTICS16 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgeliehene CDs.
        /// </summary>
        internal static string TEXT_STATISTICS17 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtwert der CD-Sammlung.
        /// </summary>
        internal static string TEXT_STATISTICS18 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl der Tracks.
        /// </summary>
        internal static string TEXT_STATISTICS2 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Längster Track.
        /// </summary>
        internal static string TEXT_STATISTICS3 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kürzester Track.
        /// </summary>
        internal static string TEXT_STATISTICS4 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchschnittliche Tracklänge.
        /// </summary>
        internal static string TEXT_STATISTICS5 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchschnittliche Anzahl Tracks pro CD.
        /// </summary>
        internal static string TEXT_STATISTICS6 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl der CDs.
        /// </summary>
        internal static string TEXT_STATISTICS7 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Sampler CDs.
        /// </summary>
        internal static string TEXT_STATISTICS8 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD mit größter Anzahl von Tracks.
        /// </summary>
        internal static string TEXT_STATISTICS9 {
            get {
                return ResourceManager.GetString("TEXT_STATISTICS9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfache Statistiken.
        /// </summary>
        internal static string TEXT_TEXTOVERVIEW {
            get {
                return ResourceManager.GetString("TEXT_TEXTOVERVIEW", resourceCulture);
            }
        }
    }
}
